# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190215_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city_Name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_pic',
            new_name='city_Pic',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country_Id',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='hotel_Name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_pic',
            new_name='hotel_Pic',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='city_id',
            new_name='city_Id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_name',
            new_name='loc_Name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_pic',
            new_name='loc_Pic',
        ),
    ]
