# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190215_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='description',
            new_name='city_Description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='city_Id',
            new_name='city_Name',
        ),
    ]
