# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20190215_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='cityhotel',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='location',
            name='loc_Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
