# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20190215_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_Pic',
            field=models.ImageField(max_length=250, upload_to='static/cities/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_Pic',
            field=models.ImageField(max_length=250, upload_to='static/countries/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Pic',
            field=models.ImageField(max_length=250, upload_to='static/hotels/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_Pic',
            field=models.ImageField(max_length=250, upload_to='static/locations/'),
        ),
    ]
