# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0007_auto_20190215_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Bad'), (2, 'Below Average'), (3, 'Average'), (4, 'Very Good'), (5, 'Excelent')], default=3)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
