# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20190215_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(max_length=3)),
                ('room_type', models.CharField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple')], max_length=2)),
                ('hotel_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Hotel')),
            ],
        ),
    ]
