# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_usercityrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercityrate',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='usercityrate',
            old_name='user_id',
            new_name='user',
        ),
    ]
