# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20190216_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercityrate',
            name='rate',
            field=models.IntegerField(default=3),
        ),
    ]
