# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 19:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0015_usercarrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarRent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('dropoff_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_loc', to='places.Location')),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_loc', to='places.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercarrent',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCarRent',
        ),
    ]
