# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_room'),
        ('places', '0017_auto_20190216_1955'),
    ]

    operations = [
    ]
