# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_merge_20190217_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_Pic',
            field=models.ImageField(max_length=250, upload_to='cities'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_Pic',
            field=models.ImageField(max_length=250, upload_to='countries'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Pic',
            field=models.ImageField(max_length=250, upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_Pic',
            field=models.ImageField(max_length=250, upload_to='locations'),
        ),
    ]
