# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-17 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20190217_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotelreservation',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple')]),
        ),
        migrations.AlterField(
            model_name='userhotelreservation',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
