# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-18 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20190217_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhotelreservation',
            old_name='res_Date',
            new_name='from_Date',
        ),
        migrations.AddField(
            model_name='userhotelreservation',
            name='to_Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
