# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_userhotelres'),
        ('places', '0022_auto_20190218_0952'),
        ('places', '0019_auto_20190218_0800'),
    ]

    operations = [
    ]
