# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_merge_20190220_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhotelres',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='userhotelres',
            name='user',
        ),
        migrations.AlterField(
            model_name='usercityrate',
            name='rate',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Bad'), (2, 'Below Average'), (3, 'Average'), (4, 'Very Good'), (5, 'Excellent')], default=0),
        ),
        migrations.DeleteModel(
            name='UserHotelRes',
        ),
    ]
