INSERT INTO places_country(country_Name) VALUES ('United States');
INSERT INTO places_country(country_Name) VALUES ('Samoa');
INSERT INTO places_country(country_Name) VALUES ('Niue');
INSERT INTO places_country(country_Name) VALUES ('Cook Islands');
INSERT INTO places_country(country_Name) VALUES ('French Polynesia');
INSERT INTO places_country(country_Name) VALUES ('Canada');
INSERT INTO places_country(country_Name) VALUES ('Mexico');
INSERT INTO places_country(country_Name) VALUES ('Chile');
INSERT INTO places_country(country_Name) VALUES ('Guatemala');
INSERT INTO places_country(country_Name) VALUES ('El Salvador');
INSERT INTO places_country(country_Name) VALUES ('Belize');
INSERT INTO places_country(country_Name) VALUES ('Honduras');
INSERT INTO places_country(country_Name) VALUES ('Nicaragua');
INSERT INTO places_country(country_Name) VALUES ('Costa Rica');
INSERT INTO places_country(country_Name) VALUES ('Cuba');
INSERT INTO places_country(country_Name) VALUES ('Malaysia');
INSERT INTO places_country(country_Name) VALUES ('Ecuador');
INSERT INTO places_country(country_Name) VALUES ('Panama');
INSERT INTO places_country(country_Name) VALUES ('The Bahamas');
INSERT INTO places_country(country_Name) VALUES ('Peru');
INSERT INTO places_country(country_Name) VALUES ('Jamaica');
INSERT INTO places_country(country_Name) VALUES ('Colombia');
INSERT INTO places_country(country_Name) VALUES ('Venezuela');
INSERT INTO places_country(country_Name) VALUES ('Turks and Caicos Islands');
INSERT INTO places_country(country_Name) VALUES ('Aruba');
INSERT INTO places_country(country_Name) VALUES ('Dominican Republic');
INSERT INTO places_country(country_Name) VALUES ('Brazil');
INSERT INTO places_country(country_Name) VALUES ('Netherlands Antilles');
INSERT INTO places_country(country_Name) VALUES ('Argentina');
INSERT INTO places_country(country_Name) VALUES ('Bolivia');
INSERT INTO places_country(country_Name) VALUES ('Puerto Rico');
INSERT INTO places_country(country_Name) VALUES ('Grenada');
INSERT INTO places_country(country_Name) VALUES ('Bermuda');
INSERT INTO places_country(country_Name) VALUES ('British Virgin Islands');
INSERT INTO places_country(country_Name) VALUES ('Anguilla');
INSERT INTO places_country(country_Name) VALUES ('Guadeloupe');
INSERT INTO places_country(country_Name) VALUES ('Trinidad and Tobago');
INSERT INTO places_country(country_Name) VALUES ('Dominica');
INSERT INTO places_country(country_Name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO places_country(country_Name) VALUES ('St. Lucia');
INSERT INTO places_country(country_Name) VALUES ('Barbados');
INSERT INTO places_country(country_Name) VALUES ('Hong Kong');
INSERT INTO places_country(country_Name) VALUES ('Paraguay');
INSERT INTO places_country(country_Name) VALUES ('Réunion');
INSERT INTO places_country(country_Name) VALUES ('Uruguay');
INSERT INTO places_country(country_Name) VALUES ('Suriname');
INSERT INTO places_country(country_Name) VALUES ('French Guiana');
INSERT INTO places_country(country_Name) VALUES ('Greenland');
INSERT INTO places_country(country_Name) VALUES ('Italy');
INSERT INTO places_country(country_Name) VALUES ('Portugal');
INSERT INTO places_country(country_Name) VALUES ('Iceland');
INSERT INTO places_country(country_Name) VALUES ('Senegal');
INSERT INTO places_country(country_Name) VALUES ('The Gambia');
INSERT INTO places_country(country_Name) VALUES ('Mauritania');
INSERT INTO places_country(country_Name) VALUES ('Guinea-Bissau');
INSERT INTO places_country(country_Name) VALUES ('Guinea');
INSERT INTO places_country(country_Name) VALUES ('Sierra Leone');
INSERT INTO places_country(country_Name) VALUES ('Western Sahara');
INSERT INTO places_country(country_Name) VALUES ('Liberia');
INSERT INTO places_country(country_Name) VALUES ('Mali');
INSERT INTO places_country(country_Name) VALUES ('Morocco');
INSERT INTO places_country(country_Name) VALUES ('Faroe Islands');
INSERT INTO places_country(country_Name) VALUES ('Ireland');
INSERT INTO places_country(country_Name) VALUES ('Spain');
INSERT INTO places_country(country_Name) VALUES ('United Kingdom');
INSERT INTO places_country(country_Name) VALUES ('Gibraltar');
INSERT INTO places_country(country_Name) VALUES ('Côte d''Ivoire');
INSERT INTO places_country(country_Name) VALUES ('Australia');
INSERT INTO places_country(country_Name) VALUES ('France');
INSERT INTO places_country(country_Name) VALUES ('Burkina Faso');
INSERT INTO places_country(country_Name) VALUES ('Ghana');
INSERT INTO places_country(country_Name) VALUES ('Togo');
INSERT INTO places_country(country_Name) VALUES ('Niger');
INSERT INTO places_country(country_Name) VALUES ('Benin');
INSERT INTO places_country(country_Name) VALUES ('Algeria');
INSERT INTO places_country(country_Name) VALUES ('Nigeria');
INSERT INTO places_country(country_Name) VALUES ('Netherlands');
INSERT INTO places_country(country_Name) VALUES ('Belgium');
INSERT INTO places_country(country_Name) VALUES ('Norway');
INSERT INTO places_country(country_Name) VALUES ('Switzerland');
INSERT INTO places_country(country_Name) VALUES ('Germany');
INSERT INTO places_country(country_Name) VALUES ('Monaco');
INSERT INTO places_country(country_Name) VALUES ('Philippines');
INSERT INTO places_country(country_Name) VALUES ('Gabon');
INSERT INTO places_country(country_Name) VALUES ('Liechtenstein');
INSERT INTO places_country(country_Name) VALUES ('Cameroon');
INSERT INTO places_country(country_Name) VALUES ('Tunisia');
INSERT INTO places_country(country_Name) VALUES ('Denmark');
INSERT INTO places_country(country_Name) VALUES ('Austria');
INSERT INTO places_country(country_Name) VALUES ('Sweden');
INSERT INTO places_country(country_Name) VALUES ('Libya');
INSERT INTO places_country(country_Name) VALUES ('Angola');
INSERT INTO places_country(country_Name) VALUES ('Czech Republic');
INSERT INTO places_country(country_Name) VALUES ('Malta');
INSERT INTO places_country(country_Name) VALUES ('Slovenia');
INSERT INTO places_country(country_Name) VALUES ('Chad');
INSERT INTO places_country(country_Name) VALUES ('Republic of the Congo');
INSERT INTO places_country(country_Name) VALUES ('Democratic Republic of the Congo');
INSERT INTO places_country(country_Name) VALUES ('Svalbard and Jan Mayen');
INSERT INTO places_country(country_Name) VALUES ('Croatia');
INSERT INTO places_country(country_Name) VALUES ('Slovakia');
INSERT INTO places_country(country_Name) VALUES ('Bosnia and Herzegovina');
INSERT INTO places_country(country_Name) VALUES ('South Africa');
INSERT INTO places_country(country_Name) VALUES ('Central African Republic');
INSERT INTO places_country(country_Name) VALUES ('Hungary');
INSERT INTO places_country(country_Name) VALUES ('Montenegro');
INSERT INTO places_country(country_Name) VALUES ('Albania');
INSERT INTO places_country(country_Name) VALUES ('Poland');
INSERT INTO places_country(country_Name) VALUES ('Serbia');
INSERT INTO places_country(country_Name) VALUES ('Russia');
INSERT INTO places_country(country_Name) VALUES ('Kosovo');
INSERT INTO places_country(country_Name) VALUES ('Macedonia');
INSERT INTO places_country(country_Name) VALUES ('Bulgaria');
INSERT INTO places_country(country_Name) VALUES ('Greece');
INSERT INTO places_country(country_Name) VALUES ('Finland');
INSERT INTO places_country(country_Name) VALUES ('Ukraine');
INSERT INTO places_country(country_Name) VALUES ('Latvia');
INSERT INTO places_country(country_Name) VALUES ('Estonia');
INSERT INTO places_country(country_Name) VALUES ('Lithuania');
INSERT INTO places_country(country_Name) VALUES ('Zambia');
INSERT INTO places_country(country_Name) VALUES ('Botswana');
INSERT INTO places_country(country_Name) VALUES ('Romania');
INSERT INTO places_country(country_Name) VALUES ('Syria');
INSERT INTO places_country(country_Name) VALUES ('Lesotho');
INSERT INTO places_country(country_Name) VALUES ('Belarus');
INSERT INTO places_country(country_Name) VALUES ('Zimbabwe');
INSERT INTO places_country(country_Name) VALUES ('Turkey');
INSERT INTO places_country(country_Name) VALUES ('Burundi');
INSERT INTO places_country(country_Name) VALUES ('Moldova');
INSERT INTO places_country(country_Name) VALUES ('Egypt');
INSERT INTO places_country(country_Name) VALUES ('Rwanda');
INSERT INTO places_country(country_Name) VALUES ('Swaziland');
INSERT INTO places_country(country_Name) VALUES ('Sudan');
INSERT INTO places_country(country_Name) VALUES ('Mozambique');
INSERT INTO places_country(country_Name) VALUES ('Tanzania');
INSERT INTO places_country(country_Name) VALUES ('Cyprus');
INSERT INTO places_country(country_Name) VALUES ('Malawi');
INSERT INTO places_country(country_Name) VALUES ('Palestine');
INSERT INTO places_country(country_Name) VALUES ('Israel');
INSERT INTO places_country(country_Name) VALUES ('Lebanon');
INSERT INTO places_country(country_Name) VALUES ('Jordan');
INSERT INTO places_country(country_Name) VALUES ('Kenya');
INSERT INTO places_country(country_Name) VALUES ('Ethiopia');
INSERT INTO places_country(country_Name) VALUES ('Eritrea');
INSERT INTO places_country(country_Name) VALUES ('Saudi Arabia');
INSERT INTO places_country(country_Name) VALUES ('Georgia');
INSERT INTO places_country(country_Name) VALUES ('Comoros');
INSERT INTO places_country(country_Name) VALUES ('Iraq');
INSERT INTO places_country(country_Name) VALUES ('Somalia');
INSERT INTO places_country(country_Name) VALUES ('Armenia');
INSERT INTO places_country(country_Name) VALUES ('Mayotte');
INSERT INTO places_country(country_Name) VALUES ('Iran');
INSERT INTO places_country(country_Name) VALUES ('Azerbaijan');
INSERT INTO places_country(country_Name) VALUES ('Madagascar');
INSERT INTO places_country(country_Name) VALUES ('Bahrain');
INSERT INTO places_country(country_Name) VALUES ('Qatar');
INSERT INTO places_country(country_Name) VALUES ('United Arab Emirates');
INSERT INTO places_country(country_Name) VALUES ('Mauritius');
INSERT INTO places_country(country_Name) VALUES ('Turkmenistan');
INSERT INTO places_country(country_Name) VALUES ('Oman');
INSERT INTO places_country(country_Name) VALUES ('Uzbekistan');
INSERT INTO places_country(country_Name) VALUES ('Afghanistan');
INSERT INTO places_country(country_Name) VALUES ('Pakistan');
INSERT INTO places_country(country_Name) VALUES ('India');
INSERT INTO places_country(country_Name) VALUES ('Tajikistan');
INSERT INTO places_country(country_Name) VALUES ('Kazakhstan');
INSERT INTO places_country(country_Name) VALUES ('Kyrgyzstan');
INSERT INTO places_country(country_Name) VALUES ('Sri Lanka');
INSERT INTO places_country(country_Name) VALUES ('Nepal');
INSERT INTO places_country(country_Name) VALUES ('China');
INSERT INTO places_country(country_Name) VALUES ('Bhutan');
INSERT INTO places_country(country_Name) VALUES ('Bangladesh');
INSERT INTO places_country(country_Name) VALUES ('Indonesia');
INSERT INTO places_country(country_Name) VALUES ('Myanmar');
INSERT INTO places_country(country_Name) VALUES ('Thailand');
INSERT INTO places_country(country_Name) VALUES ('Laos');
INSERT INTO places_country(country_Name) VALUES ('Singapore');
INSERT INTO places_country(country_Name) VALUES ('Cambodia');
INSERT INTO places_country(country_Name) VALUES ('Vietnam');
INSERT INTO places_country(country_Name) VALUES ('Mongolia');
INSERT INTO places_country(country_Name) VALUES ('Macau');
INSERT INTO places_country(country_Name) VALUES ('Brunei');
INSERT INTO places_country(country_Name) VALUES ('Taiwan');
INSERT INTO places_country(country_Name) VALUES ('North Korea');
INSERT INTO places_country(country_Name) VALUES ('South Korea');
INSERT INTO places_country(country_Name) VALUES ('Japan');
INSERT INTO places_country(country_Name) VALUES ('Palau');
INSERT INTO places_country(country_Name) VALUES ('Papua New Guinea');
INSERT INTO places_country(country_Name) VALUES ('Federated States of Micronesia');
INSERT INTO places_country(country_Name) VALUES ('Solomon Islands');
INSERT INTO places_country(country_Name) VALUES ('New Caledonia');
INSERT INTO places_country(country_Name) VALUES ('New Zealand');
INSERT INTO places_country(country_Name) VALUES ('Marshall Islands');
INSERT INTO places_country(country_Name) VALUES ('Fiji');
INSERT INTO places_country(country_Name) VALUES ('Tuvalu');
INSERT INTO places_country(country_Name) VALUES ('Tonga');
INSERT INTO places_country(country_Name) VALUES ('Haiti');
INSERT INTO places_country(country_Name) VALUES ('Martinique');
INSERT INTO places_country(country_Name) VALUES ('Andorra');
INSERT INTO places_country(country_Name) VALUES ('Luxembourg');
INSERT INTO places_country(country_Name) VALUES ('San Marino');
INSERT INTO places_country(country_Name) VALUES ('Djibouti');
INSERT INTO places_country(country_Name) VALUES ('Yemen');
INSERT INTO places_country(country_Name) VALUES ('Kuwait');
INSERT INTO places_country(country_Name) VALUES ('Republic of Maldives');
INSERT INTO places_country(country_Name) VALUES ('Republic of Palau');
INSERT INTO places_country(country_Name) VALUES ('Nauru');
INSERT INTO places_country(country_Name) VALUES ('Vanuatu');
INSERT INTO places_country(country_Name) VALUES ('Wallis and Futuna');